### ISSUE TITLE
metrics functions gives 'numpy.int64' object is not iterable

### ISSUE THREAD

**Issue by yonatanbitton** [TeamHG-Memex/sklearn-crfsuite#46]
Hi 

I want to do simple usage of your function. 

My data, y_pred and y_test are lists of lists, in length of 50. 
(Each inner list in different length)

a. `res = sklearn_crfsuite.metrics.flat_classification_report(y_test, y_pred, digits=3)`
```
Traceback (most recent call last):
  File "C:\Users\PC-1\.conda\envs\KerasEnv36\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-b25a149ce4c7>", line 1, in <module>
    res = sklearn_crfsuite.metrics.flat_classification_report(y_test, y_pred, digits=3)
  File "C:\Users\PC-1\.conda\envs\KerasEnv36\lib\site-packages\sklearn_crfsuite\metrics.py", line 11, in wrapper
    y_true_flat = flatten(y_true)
  File "C:\Users\PC-1\.conda\envs\KerasEnv36\lib\site-packages\sklearn_crfsuite\utils.py", line 12, in flatten
    return list(chain.from_iterable(y))
TypeError: 'numpy.int64' object is not iterable

```

What is the problem ? Thanks

**Comment by asfakali** [comment]
I got same issue. Any solution?
